# -*- coding: utf-8 -*-
"""NDWI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bIZpRhRMLccb6Q-Pz9bOQ49ddycm_kFt
"""

#installing geemap
!pip install geemap

#importing geemap
import geemap

#importing ee
import ee

#authentication and initialization of the connection
ee.Authenticate()
ee.Initialize()

#displaying normalized difference water index
#display gee map
Display = geemap.Map()
#Display

#dataset of boundary of all countries
allcountries = ee.FeatureCollection("USDOS/LSIB_SIMPLE/2017");

#getting ndwi dataset
ndwi_set = ee.ImageCollection("LANDSAT/LC8_L1T_8DAY_NDWI")
#filtering boundary of the Sri Lanka
aoi = allcountries.filter(ee.Filter.eq("country_na", "Sri Lanka"));

#setting ndwi for the perspective
NDWI = ndwi_set.select('NDWI')\
 .filterDate('2016-01-01', '2017-01-01')\
 .reduce(ee.Reducer.mean())\
 .clip(aoi)

#visualizing the colors of ndwi according to the range
colVis = {
  'min': 0.0,
  'max': 1.0,
  'palette': ['0000ff', '00ffff', 'ffff00', 'ff0000', 'ffffff'],
};

#displaying of the ndwi map
Display.addLayer(aoi)
Display.addLayer(NDWI, colVis)
Display.centerObject(aoi, 8)
Display